export const GETTING_PRODUCT_REQUEST  = 'GETTING_PRODUCT_REQUEST';
export const GETTING_PRODUCT_ERROR    = 'GETTING_PRODUCT_ERROR';
export const GETTING_PRODUCT_SUCCESS  = 'GETTING_PRODUCT_SUCCESS';
export const GETTING_PRODUCTS_REQUEST  = 'GETTING_PRODUCTS_REQUEST';
export const GETTING_PRODUCTS_ERROR    = 'GETTING_PRODUCTS_ERROR';
export const GETTING_PRODUCTS_SUCCESS  = 'GETTING_PRODUCTS_SUCCESS';