export const GET_USERS_COUNT_REQUEST    = 'GET_USERS_COUNT_REQUEST';
export const GET_USERS_COUNT_ERROR      = 'GET_USERS_COUNT_ERROR';
export const GET_USERS_COUNT_SUCCESS    = 'GET_USERS_COUNT_SUCCESS';